### PR TITLE
[snowflake] Support `FROM (table_name) alias`

### LINKED ISSUE #223: Fail to parse - "select * from (table_name) alias" (Snowflake)
Related to https://github.com/ballista-compute/sqlparser-rs/issues/154

sqlparser now parses `select * from (table_name)`. However, it does not parse `select * from (table_name) alias`. 

Would it make sense to add this functionality? If so, would that mean adding an `alias` field to `TableWithJoins`?

### PR DESCRIPTION
**Pull request by eyalleshem**
Initially discussed in https://github.com/ballista-compute/sqlparser-rs/issues/223 and  https://github.com/ballista-compute/sqlparser-rs/pull/244. Closes #223.

The description copied from the commit:

Snowflake diverges from the standard and from most of the other implementations by allowing extra parentheses not only around a join, but around lone table names (e.g. `FROM (mytable [AS alias])`) and around derived tables (e.g. `FROM ((SELECT ...)  [AS alias])`) as well.

Initially this was implemented in https://github.com/ballista-compute/sqlparser-rs/issues/154 by (ab)using `TableFactor::NestedJoin` to represent anything nested in extra set of parens.

Afterwards we learned in https://github.com/ballista-compute/sqlparser-rs/issues/223 that in cases of such extraneous nesting Snowflake allows specifying the alias both inside and outside parens, but not both - consider:

    FROM (table_factor AS inner_alias) AS outer_alias

We've considered implementing this by changing `TableFactor::NestedJoin` to a `TableFactor::Nested { inner: TableWithJoins, alias: Option<TableAlias> }`, but that seemed too generic, as no known dialect supports duplicate aliases, as shown above, nor naming nested joins `(foo NATURAL JOIN bar) alias`. So we decided on making a smaller change (with no modifications to the AST), that is also more appropriate to the contributors to the Snowflake dialect:

1) Revert #154 by rejecting `FROM (table or derived table)` in most dialects.

2) For `dialect_of!(self is SnowflakeDialect | GenericDialect)` parse
and strip the extraneous parentheses:

   `(mytable) AS alias` -> `(mytable AS alias)`

### CODE REVIEW

File: tests/sqlparser_common.rs [hunk 1]
```diff
@@ -17,6 +17,14 @@
 //! that 1) it's either standard or widely supported and 2) it can be parsed by
 //! sqlparser regardless of the chosen dialect (i.e. it doesn't conflict with
 //! dialect-specific parsing rules).
+//!
+//!
```
Comment (nickolay) [inline tests/sqlparser_common.rs:21]: Any reason for this addition?

File: tests/sqlparser_common.rs [hunk 2]
```diff
@@ -17,6 +17,14 @@
...
+
+#[macro_use]
+#[path = "utils/mod.rs"]
+mod utils;
+
+use utils::*;
```
Comment (nickolay) [inline tests/sqlparser_common.rs:27]: There's `test_utils.rs` for that already.

File: tests/sqlparser_snowflake.rs [hunk 3]
```diff
@@ -9,9 +9,26 @@
...
+#[path = "utils/mod.rs"]
+mod utils;
+
 use sqlparser::ast::*;
 use sqlparser::dialect::{GenericDialect, SnowflakeDialect};
+use sqlparser::parser::ParserError;
 use sqlparser::test_utils::*;
+use utils::*;
+
+fn table_alias(alias: &str) -> TableAlias {
```
Comment (nickolay) [inline tests/sqlparser_snowflake.rs:23]: Maybe keep `table(name)` as is to avoid changes to existing tests, and add a `table_with_alias(table, alias)` instead?

File: tests/sqlparser_snowflake.rs [hunk 4]
```diff
@@ -24,6 +41,120 @@ fn test_snowflake_create_table() {
     }
 }
 
+fn get_from_section_from_select_query(query: &str) -> Vec<TableWithJoins> {
```
Comment (nickolay) [inline tests/sqlparser_snowflake.rs:44]: Can't you use `verified_only_select(sql).from` instead of creating a new helper?

File: tests/sqlparser_common.rs [hunk 5]
```diff
@@ -2492,26 +2473,6 @@ fn parse_derived_tables() {
             }],
         }))
     );
-
-    // Nesting a subquery in parentheses is non-standard, but supported in Snowflake SQL
-    let sql = "SELECT * FROM ((SELECT 1) AS t)";
```
Comment (nickolay) [inline tests/sqlparser_common.rs:2497]: To reiterate, it's hard to review when you change code at the same time you move it around. I forgot about this when reviewing the PR for the new dialect, but the idea was to do the moves there.

I found the new location of the other two moved tests, but not this one.. Where was this test case moved?

File: tests/sqlparser_snowflake.rs [hunk 6]
```diff
@@ -24,6 +41,120 @@ fn test_snowflake_create_table() {
...
+        }
+    );
+}
+
+#[test]
+fn test_single_table_in_parenthesis() {
+    //Parenthesized table names are non-standard, but supported in Snowflake SQL
+    let from = get_from_section_from_select_query("SELECT * FROM (a NATURAL JOIN (b))");
+
+    assert_eq!(from[0].relation, nest!(table("a", None), table("b", None)));
```
Comment (nickolay) [inline tests/sqlparser_snowflake.rs:82]: Better use `only(select.from)`, as `from[0]` doesn't check there are no other items in the FROM.

File: tests/sqlparser_snowflake.rs [hunk 7]
```diff
@@ -24,6 +41,120 @@ fn test_snowflake_create_table() {
...
+
+    let from = get_from_section_from_select_query("SELECT * FROM (a NATURAL JOIN ((b)))");
```
Comment (nickolay) [inline tests/sqlparser_snowflake.rs:84]: This used to have a comment:
```
// Double parentheses around table names are non-standard, but supported in Snowflake SQL
```

File: tests/sqlparser_snowflake.rs [hunk 8]
```diff
@@ -24,6 +41,120 @@ fn test_snowflake_create_table() {
...
+    assert_eq!(from[0].relation, nest!(table("a", None), table("b", None)));
+}
+
+#[test]
+fn test_single_table_in_parenthesis_with_alias() {
+    let sql = "SELECT * FROM (a NATURAL JOIN (b) c )";
+    let table_with_joins = get_from_section_from_select_query(sql)[0].clone();
```
Comment (nickolay) [inline tests/sqlparser_snowflake.rs:91]: Shouldn't need the `clone`s.

File: tests/sqlparser_snowflake.rs [hunk 9]
```diff
@@ -24,6 +41,120 @@ fn test_snowflake_create_table() {
...
+    let res = snowflake().parse_sql_statements("SELECT * FROM (a b) c");
+    assert_eq!(
+        ParserError::ParserError("duplicate alias b".to_string()),
+        res.unwrap_err()
+    );
+}
+
+fn snowflake() -> TestedDialects {
+    TestedDialects {
+        // we don't have a separate SQLite dialect, so test only the generic dialect for now
```
Comment (nickolay) [inline tests/sqlparser_snowflake.rs:153]: Please remove.

File: tests/sqlparser_common.rs (hunk 1 above)
Comment (eyalleshem) [reply tests/sqlparser_common.rs]: sorry , removed

File: tests/sqlparser_common.rs (hunk 2 above)
Comment (eyalleshem) [reply tests/sqlparser_common.rs]: The actual reason that i don't use the test util is that i want to share the macro between the test , 
And if I understand it correct , the `src` and the the `test` are not considered in the same crate , so i can export macro only via `#[macro_export]` directive, but that mean the macro will be available not only  for the test but to all users of the lib , and that something that i want to avoid (please correct me if i wrong..). 
Anyway - I moved the join and table macros to `test_utils.rs` and change the `utils` dir that i crated to `macros` dir, hope you ok with that. 
btw - why `test_util.rs` located inside the source ?

File: tests/sqlparser_snowflake.rs (hunk 3 above)
Comment (eyalleshem) [reply tests/sqlparser_snowflake.rs]: Done

File: tests/sqlparser_common.rs (hunk 5 above)
Comment (eyalleshem) [reply tests/sqlparser_common.rs:2497]: Sorry about that , i also comment in the [previous pr](https://github.com/ballista-compute/sqlparser-rs/pull/259#issuecomment-671435447) that i don't sure what needed to be in the test (now i am understand :) ) . 

Anyway added also this test ..

File: tests/sqlparser_snowflake.rs (hunk 6 above)
Comment (eyalleshem) [reply tests/sqlparser_snowflake.rs]: Done

File: tests/sqlparser_snowflake.rs (hunk 4 above)
Comment (eyalleshem) [reply tests/sqlparser_snowflake.rs:33]: It's a problem to use it because we remove the information about [ we ignore the information about  the redundant parenthesis in the AST ](https://github.com/ballista-compute/sqlparser-rs/issues/223#issuecomment-666334528)  , so the input sql will   be different than the output .

File: tests/sqlparser_snowflake.rs (hunk 7 above)
Comment (eyalleshem) [reply tests/sqlparser_snowflake.rs:86]: This comment relevant to both test in the function , so i put here as the first line in the function , and then blank line , so it's relate to the function and not specific line ..

File: tests/sqlparser_snowflake.rs (hunk 8 above)
Comment (eyalleshem) [reply tests/sqlparser_snowflake.rs]: done

File: tests/sqlparser_snowflake.rs (hunk 9 above)
Comment (eyalleshem) [reply tests/sqlparser_snowflake.rs]: done , sorry - a  rebase issue

**Comment by nickolay** [comment]
I first rebased this onto `main` without changes, then split into two commits (moving things around and implementing the new functionality), as I wanted to do all along...

**Comment by nickolay** [comment]
Regarding the need to share helper macros, as well as helper functions, discussed in https://github.com/ballista-compute/sqlparser-rs/pull/260#discussion_r470006301 -- I added a commit https://github.com/ballista-compute/sqlparser-rs/pull/260/commits/a3a0d7b1de791091786a52ebfe2dec9654f9cc66 that demonstrates how I'd like to solve this. I added some comments that I hope will explain my reasoning, please let me know if they're not clear.

The second part of the PR I want to look over again before merging.

**Comment by eyalsatori** [comment]
Thanks a lot for the rebasing and the fixes!  
The solution of the test_utils indeed much more elegant . 

Is there any change needed from me ,  or you just want to continue review it?

**Comment by nickolay** [comment]
No, I was just running out of time that night, and wanted to share the part I believed to be ready. I'll try to get to the other one sometime "soon"...

**Comment by nickolay** [comment]
> > Can't you use verified_only_select(sql).from instead of creating a new helper?
>
> It's a problem to use it because we remove the information about we ignore the information about the redundant parenthesis in the AST , so the input sql will be different than the output .

I don't know why it took me so long to realize it, but we use `one_statement_parses_to` in cases like this. I added commits that do that to this PR and if you're OK with this, I'm ready to merge.

**Comment by eyalsatori** [comment]
I am ok with that , 
Thanks a lot :)

**Review by nickolay — APPROVED** [review]

**Comment by waitingkuo** [comment]
@eyalleshem  @nickolay i made a pull request #551 for nested table with alias
